# Generated by Django 2.1.3 on 2018-11-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20181113_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_inserted',
            field=models.DateTimeField(default='2018-11-13 06:07'),
        ),
    ]
