version: '3'

services:
#  nginx:
#    image: nginx:latest
#    hostname: nginx
#    ports:
#      - "8080:80"
#    environment:
#      - NGINX_HOST=foobar.com
#      - NGINX_PORT=80
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  psql:
    image: postgres:latest
    restart: always
    hostname: psql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Admin14801612
      - POSTGRES_DB=chat
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    restart: always
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./data/mongo:/var/lib/mongo

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - HOST_PORT_RABBIT=5672
      - HOST_PORT_RABBIT_MGMT=15672
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - HOST_PATH_RABBIT_DATADIR=./data/rabbitmq
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  django:
    hostname: django
    build: deploy/python/
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/chat
    ports:
      - "8000:8000"
    depends_on:
      - psql
      - mongo
      - rabbitmq
    links:
      - psql
      - mongo
      - rabbitmq

